### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by mattgreen** [siuying/NanoStoreInMotion#14]
I'm having trouble launching the app after adding the gem to my bundle. I always get this error:

```
*** Terminating app due to uncaught exception 'NameError', reason: 'undefined method `discardUnsavedChanges' for class `NSFNanoStore' (NameError)
```

I'm targeting iOS 5.1 with RubyMotion 1.25.

**Comment by siuying** [comment]
Please check if your project used any pods. If it do not use cocoa pods, you will have to manually add NanoStore pod in the project. Check the readme for more details.

**Comment by siuying** [comment]
Hi, were you able to resolve the issue?

**Comment by mattgreen** [comment]
No, I'm not using it at the moment. I will close this issue for now and reopen if I encounter it again.
