### ISSUE TITLE
find not returning anything

### ISSUE THREAD

**Issue by malkomalko** [siuying/NanoStoreInMotion#15]
I have a few different models and for some reason my Listing model will not return anything when I do a Listing.all.

Listing.count shows 0.

However if I look in the db file, it looks like the RBListing is there fine with all the values.

**Comment by malkomalko** [comment]
why did it save Listing as RBListing?  That seems to be the problem.

``` rb
class Listing < NanoStore::Model
  .... my attributes
end
```

Listing.bare_class_name => "Listing"
Listing.store.objectsOfClassNamed(Listing.bare_class_name) => []

Listing.store.objectsOfClassNamed("RBListing") => [#Listing:0xc553e00]

**Comment by siuying** [comment]
I guess it has some name conflicts, somewhere else in rubymotion use the
name Listing.

Can you try namespace the Listing class and try again?

**Comment by malkomalko** [comment]
namespaced to Models::Listing and it's doing the same thing.  I changed it to Property and it worked fine, but it's very interesting.

**Comment by siuying** [comment]
can you send me a test case? I have tried to reproduce the error but no luck: 70633e3

**Comment by siuying** [comment]
closing this until we got update.
