### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by toamitkumar** [siuying/NanoStoreInMotion#17]
Undefined symbols for architecture i386:
  "_NSFSetIsDebugOn", referenced from:
      _MREP_95211FC97BA34C5FA92C2C43067D0E4A in nano_store.rb.o

I am getting this error.
I remember it was reported but dont remember what resolved the issue.

**Comment by siuying** [comment]
Have you include Cocoapods 'NanoStore' in your project? Have you run 'rake
clean' to clean up the old build ?

Amit Kumar notifications@github.com 於 31 Oct, 2012 5:53 PM 寫道：

Undefined symbols for architecture i386:
"_NSFSetIsDebugOn", referenced from:
_MREP_95211FC97BA34C5FA92C2C43067D0E4A in nano_store.rb.o

I am getting this error.
I remember it was reported but dont remember what resolved the issue.

—
Reply to this email directly or view it on
GitHubhttps://github.com/siuying/NanoStoreInMotion/issues/17.

**Comment by toamitkumar** [comment]
Thats surprising, I had done `rake clean` twice before and it did not work
Worked now.
I am puzzled. Nevermind

**Comment by defvol** [comment]
`rake clean` did the trick for me

**Comment by jankeesvw** [comment]
Got the same problem, `rake clean` does not work for me...
