### ISSUE TITLE
Is there any way to create a relationship with a bag and StoreNano::Model

### ISSUE THREAD

**Issue by naoyamakino** [siuying/NanoStoreInMotion#19]
how can we create an instance of NanoStore::Model with one bag associated with it?
from the example below, we want to create a User has one bag which contains instances of Car. Is this possible?

``` ruby
 class Car < NanoStore::Model
    attribute :name
    attribute :age
  end

  class User < NanoStore::Model
    attribute :name
    attribute :age
    attribute :created_at
    attribute :cars #we want this to be a link to a bag.
  end
```

**Comment by siuying** [comment]
I've not needed this kind of usage yet, and this is not possible currently in NanoStoreInMotion. You can store the key of a bag in User.cars, or maybe embed the object as dictionary there.

**Comment by arkan** [comment]
FYI, I've been working on a quick and simple implementation of relationships for NanoStoreInMotion.

https://github.com/Arkan/NanoStoreInMotion#using-relationships-basic

**Comment by naoyamakino** [comment]
@Arkan very nice, thanks for sharing!

**Comment by siuying** [comment]
Added bag method for Model which let you do something like ...

``` ruby
  class Todo < NanoStore::Model
    attribute :title
    bag :items
  end

  class TodoItem < NanoStore::Model
    attribute :completed
    attribute :text
  end
```

For details: https://github.com/siuying/NanoStoreInMotion/blob/master/spec/association_spec.rb
