### ISSUE TITLE
Where and how to setup default storage type?

### ISSUE THREAD

**Issue by jaimeiniesta** [siuying/NanoStoreInMotion#2]
I'm following the instructions on the README, but when it comes to "Set default storage type", I'm a bit lost...

Where should this be done? I mean, in what file? app_delegate? Rakefile? An initializer? 

Also, the line with "documents_path" will fail if it's not defined in the project.

Could you provide a more detailed example about this? Maybe you have a demo app?

Thanks! :)

**Comment by siuying** [comment]
It should be set before using the store. So it should be called in AppDelegate, probably inside `application(application, didFinishLaunchingWithOptions:launchOptions)`.

documents_path is defined in BubbleWrap Kernel module. If you cant see it, probably it is not loaded. Please revise your Rakefile:

``` ruby
Motion::Project::App.setup do |app|
  app.name = 'myapp'
  app.files = Dir.glob(File.join(app.project_dir, 'vendor/BubbleWrap/lib/**/*.rb')) + app.files
  app.files = Dir.glob(File.join(app.project_dir, 'vendor/NanoStoreInMotion/lib/**/*.rb')) + app.files
  app.pods do
    dependency 'NanoStore'
  end  
end
```

the two lines app.files = XXXXX will ensure these files are loaded before your app.

**Comment by jaimeiniesta** [comment]
Thanks, I'm closer to getting it working now. I can create items:

(main)>> Item.all
=> [#Item:0xd659fe0, #Item:0xd658690, #Item:0xd659fd0](main)>> Item.all[0].title
=> "one"
(main)>> Item.all[0].row
=> 1

But, I'm getting an error when trying to find one of them by an attribute "row":

(main)>> Item.find(:row, NSFEqualTo, "1")
=> #<NameError: uninitialized constant NSFEqualTo>

Any clue?

**Comment by jaimeiniesta** [comment]
This is the error it throws:

```
=> # <NameError: uninitialized constant NSFEqualTo>
```

**Comment by jaimeiniesta** [comment]
By the way, this is the demo I'm building, I've got NanoStore working in it:

https://github.com/jaimeiniesta/rubymotion-todo

I still need to know how to find items by attributes, though.

Thanks for building this, it's been easy to integrate!

**Comment by siuying** [comment]
This should work:

```
#    item = Item.all.sort { |a,b| a.row.to_i <=> b.row.to_i }[indexPath.row]
    item = Item.find(:row, NSFEqualTo, indexPath[1].to_s).first
```

the REPL show NSFEqualTo not found because your code do not use NSFEqualTo and Motion will not include this keyword.
