### ISSUE TITLE
Single quotes not escaped properly in .find

### ISSUE THREAD

**Issue by djcp** [siuying/NanoStoreInMotion#20]
Nice work! We're running into an issue, though, where it appears that single quotes aren't being escaped properly when passed to Model.find.

``` ruby
   Model.find(name: "I don't work properly")
```

throws an error that ultimately results in a SQLite error code 1.

``` ruby
   Model.find(name: "I don''t work properly")
```

Works properly, note the second single quote escaping the first.

**Comment by djcp** [comment]
Interestingly, we could insert names with a single quote without issue, it was just querying for them afterwards that blew up.

**Comment by siuying** [comment]
Confirmed the issue. I created an issue on NanoStore (https://github.com/tciuro/NanoStore/issues/45)

**Comment by siuying** [comment]
Thanks for report. NanoStore 2.1.8 + latest nano-store gem fix the issue. 

https://github.com/siuying/NanoStoreInMotion/compare/v0.5.0%E2%80%A6v0.5.1
