### ISSUE TITLE
uninitialized constant error

### ISSUE THREAD

**Issue by n-studio** [siuying/NanoStoreInMotion#21]
```
uninitialized constant NanoStore::Model::AssociationInstanceMethods (NameError)
Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant NanoStore::Model::AssociationInstanceMethods (NameError)
```

Occurs in empty application that just has

`require 'nano-store'`

and

`pod 'NanoStore'`

in Rakefile

nano-store works perfectly fine with 0.4.3. It occurs only with 0.5.1

**Comment by siuying** [comment]
Hi,

Which version of ruby you are using? you can try to type `ruby -v` on your command line.

**Comment by n-studio** [comment]
Hi!

`ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-darwin12.2.0]`

**Comment by siuying** [comment]
Have you try to run `rake clean` before `rake`?

**Comment by siuying** [comment]
I cannot reproduce this error. I'm also using ruby 1.9.3 so this should not be an issue. Please also use latest version (1.29) of rubymotion which automatically resolve build dependency.

**Comment by n-studio** [comment]
Ok ! So `app.detect_dependencies = false` was the cause of the error. Thank you.
Unfortunately, `app.detect_dependencies = true` gives me `stack level too deep` error.

I guess I can't use 0.5.1 until Rubymotion solves this bug.

**Comment by siuying** [comment]
@n-studio hmm, i think i can fix that by manually load the association.rb, will commit it soon.

**Comment by n-studio** [comment]
Thank you!

**Comment by siuying** [comment]
okay, 0.5.2 is release! Please see if it fixes the issue.

**Comment by n-studio** [comment]
It seems to work great! Thank you!
