### ISSUE TITLE
Rails ActiveRecord conventions

### ISSUE THREAD

**Issue by DougPuchalski** [siuying/NanoStoreInMotion#25]
Curious how you might feel about some pull requests to converge more toward established conventions, i.e. obj#attributes rather than obj#info, save returning true/false, etc.

**Comment by siuying** [comment]
Nope. This is not ActiveRecord, follow their convention just add more work.

**Comment by DougPuchalski** [comment]
Hmm I think following conventions is less work, and it would make the library more friendly. But I understand your position and will focus my contributions elsewhere.

**Comment by siuying** [comment]
Thanks!
