### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by voke** [siuying/NanoStoreInMotion#26]
If I use this setup in my Rakefile

``` ruby
require 'bundler'
Bundler.require

Motion::Project::App.setup do |app|

  app.pods do
    pod 'NanoStore', '~> 2.5.7'
  end

end
```

I get following error when running `rake`

```
Podfile tries to activate `NanoStore (~> 2.5.7)', but already activated version `2.5.2' by Podfile.
```

Since I'm using bundler I have `gem 'nano-store'` in my Gemfile.

Therefore when I run `Bundler.require` in my Rakefile nano_store is required and `app.pods.pod 'NanoStore', '2.5.2'` is executed. Source: [nano_store.rb](https://github.com/siuying/NanoStoreInMotion/blob/master/lib/nano_store.rb#L19)

I think the version of the pod should be decided by the user and not hard coded.

**Comment by siuying** [comment]
Normally the version requirement defined by nano_store gem will be '~> version', usually you can override minor version changes. This time it is define to use specifically 2.5.2 version because an issue when later version of NanoStore is used with the gem. 

meanwhile, I will update the README to avoid confusion.

**Comment by voke** [comment]
I see, so its just temporary. Anyhow, are there any benefits of specifying the pod in the Gem itself. I mean adding the pod behind the scenes vs specifying valid versions in the README. You probably gonna add it to the Rakefile anyway.

Maybe it's just me but I got confused when running `bundle install && rake` and voila now I added a new cocoapod (even if it's a dependency). :yum:  - nice gem btw

**Comment by siuying** [comment]
The advantage is you dont have to manually specify NanoStore pod in Rakefile (As long as you have other pods. if you dont have any other pods, you would still have to add that manually)

**Comment by voke** [comment]
yeah, it's just that most wrappers I have used so far leaves the pod inclusion to it's users. I don't know whats best practice.
